repo: 'responsive-photo-gallery'
canvasCourse: 'web-dev-2'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    has:
      - ['link[href*="modules.css"] + link[href*="grid.css"]', 'The `modules.css` file must come before the `grid.css` file.']
      - ['link[href*="grid.css"] + link[href*="type.css"]', 'The `grid.css` file must come before the `type.css` file.']
      - ['link[href*="type.css"] + link[href*="main.css"]', 'The `type.css` file must come before the `main.css` file.']
      - '.grid'
      - '.grid > .unit'
      - 'figure'
      - 'figcaption'
      - '.embed'
      - '.embed-item'
      - 'img[src*="placeholder-3by2.svg"]'
      - 'img[src*="placeholder-1by1.svg"]'
      - 'img[src*="placeholder-3by2.svg"]'
    search:
      - 'xs-'
      - 's-'
      - 'm-'
      - 'l-'
      - 'embed-\d+by\d+'
      - 'push-?'
      - 'pin-'
      - 'pad-?'
      - 'gutter-?'

css:
  - path: 'css/main.css'
    locked: true
  - path: 'css/grid.css'
    valid: true
    bestPractices: true
    search:
      - ['https://gridifier.web-dev.tools/#xs,4,0,0,0;s,4,25,0,0;m,4,38,1,1;l,4,60,1,1', 'The `grid.css` should be generated with Gridifier’s default settings']
  - path: 'css/type.css'
    valid: true
    bestPractices: true
    search:
      - ['https://typografier.web-dev.tools/#0,100,1.3,1.067,0;38,110,1.4,1.125,1;60,120,1.5,1.125,1;90,130,1.5,1.125,1', 'The `type.css` should be generated with Typografier’s default settings']
  - path: 'css/modules.css'
    valid: true
    bestPractices: true
    search:
      - ['https://modulifier.web-dev.tools/#responsive;images;list-group;embed;media-object;icons;hidden;positioning;nice-lists;forms;buttons;accessibility;print', 'Select all the different modules when adding Modulifier.']

screenshots:
  - path: 'index.html'
    sizes: [320, 400, 608, 960, 1440]
